### PR TITLE
Added challenge #191 to respond to issue #14

### PR DESCRIPTION
**Pull request by wolf-361**
Asks user to return a string with special characters ("String")

### CODE REVIEW

**Comment by kevmoens** [comment]
This is a great start.  I appreciate the help.  Below I have a handful of changes that I would prefer before I pull in your change.

Your description shows two tests.
Passing in Hello World! and Some string

The method GetQuotation doesn't have any parameter passed in.
Then you have one test "Test1".  You should have 2 tests to match your description.

The sumResult variable should show what the method returned instead of if it passed or failed.

Also since it is level one, move where you add the test closer to the top in the challenges class.

**Comment by wolf-361** [comment]
Ok I was not aware the description was meant to mimic the tests, sadly I don't really see what to test more ?

The method GetQuotation doesn't need to have anything passed, it only returns. Is this not what you wanted ? I feel like the other points you give me to work on are all related to this.

Right now I am only asking people to return a string that starts and ends with quotation marks, do you want me to ask them to make a function that adds the quotation marks to any string passed to it instead ?

Thanks !

**Comment by kevmoens** [comment]
If you can have your description examples be the tests, thus passing in Hello World! and looking for "Hello World!" and Some string to "Some string"

If the tests fail show what they entered verse what you expect the result should look like.

**Comment by wolf-361** [comment]
But then I'm not testing anything done in the challenge with those two ?

Presently the input from the user should look something like : 
``` c#
using System;

namespace Ellabit
{
public class Challenge 
{
	public string GetQuotation() 
	{
		    return "\"Something\""
	}
}

} 
```

**Comment by wolf-361** [comment]
I think I understood better what you wanted now ! Please let me know if not :)

If its what you wanted, do you mind adding the HACKTOBERFEST-ACCEPTED label to the PR ?

**Pull request merged**
